debian/tmp/usr/bin/yosys-filterlib usr/bin
debian/tmp/usr/bin/yosys-smtbmc usr/bin
debian/tmp/usr/bin/yosys usr/bin

debian/tmp/usr/share/yosys/simlib.v usr/share/yosys
debian/tmp/usr/share/yosys/pmux2mux.v usr/share/yosys
debian/tmp/usr/share/yosys/simcells.v usr/share/yosys
debian/tmp/usr/share/yosys/techmap.v usr/share/yosys
debian/tmp/usr/share/yosys/cells.lib usr/share/yosys
debian/tmp/usr/share/yosys/adff2dff.v usr/share/yosys

debian/tmp/usr/share/yosys/ice40 usr/share/yosys
debian/tmp/usr/share/yosys/xilinx usr/share/yosys
debian/tmp/usr/share/yosys/greenpak4 usr/share/yosys
debian/tmp/usr/share/yosys/python3/smtio.py usr/share/yosys
