usr/bin/yosys-filterlib
usr/bin/yosys-smtbmc
usr/bin/yosys

usr/share/yosys/simlib.v
usr/share/yosys/pmux2mux.v
usr/share/yosys/simcells.v
usr/share/yosys/techmap.v
usr/share/yosys/cells.lib
usr/share/yosys/adff2dff.v
usr/share/yosys/dff2ff.v

usr/share/yosys/altera_intel
usr/share/yosys/ice40
usr/share/yosys/xilinx
usr/share/yosys/greenpak4
usr/share/yosys/gowin
debian/tmp/usr/share/yosys/python3/smtio.py usr/share/yosys
